version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - './docker/zookeeper/data:/var/confluent/data'

  broker:
    image: confluentinc/cp-server:6.0.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    volumes:
      - './docker/kafka/data:/var/confluent/data'

  schema-registry:
    image: confluentinc/cp-schema-registry:6.0.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    volumes:
      - './docker/schema_registry/data:/var/confluent/data'

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

#  es01:
#    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      node.name: es01
#      discovery.seed_hosts: es01,es02,es03
#      cluster.initial_master_nodes: es01,es02,es03
#      cluster.name: mycluster
#      bootstrap.memory_lock: "true"
#      ES_JAVA_OPTS: -Xms256m -Xmx256m
#    volumes:
#      - "es-data-es01:/usr/share/elasticsearch/data"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#
#  es02:
#    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
#    ports:
#      - "9201:9200"
#      - "9301:9300"
#    environment:
#      node.name: es02
#      discovery.seed_hosts: es01,es02,es03
#      cluster.initial_master_nodes: es01,es02,es03
#      cluster.name: mycluster
#      bootstrap.memory_lock: "true"
#      ES_JAVA_OPTS: -Xms256m -Xmx256m
#    volumes:
#      - "es-data-es02:/usr/share/elasticsearch/data"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#
#  es03:
#    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
#    ports:
#      - "9202:9200"
#      - "9303:9300"
#    environment:
#      node.name: es03
#      discovery.seed_hosts: es01,es02,es03
#      cluster.initial_master_nodes: es01,es02,es03
#      cluster.name: mycluster
#      bootstrap.memory_lock: "true"
#      ES_JAVA_OPTS: -Xms256m -Xmx256m
#    volumes:
#      - "es-data-es03:/usr/share/elasticsearch/data"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana-oss:7.10.2
#    depends_on:
#      - es01
#      - es02
#      - es03
#    ports:
#      - "5601:5601"
#    environment:
#      - 'ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200","http://es03:9200"]'
